Narnia.Web/Areas/Admin/Controllers/MessageTemplateController.cs
using Microsoft.AspNetCore.Mvc;
using Narnia.Business.Messaging;
using Narnia.Web.Areas.Admin.Extensions;
using Narnia.Web.Areas.Admin.Models.Messaging;
using Narnia.Web.Framework.KendoUI;
using Narnia.Web.Framework.Mvc.Attributes;
using System;
using System.Linq;

namespace Narnia.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MessageTemplateController: BaseAdminController
    {
        private IMessageTemplateBiz _messageTemplateBiz;
        private readonly IMessageTokenProvider _messageTokenProvider;
        public MessageTemplateController(IMessageTemplateBiz messageTemplateBiz, IMessageTokenProvider messageTokenProvider)
        {
            _messageTemplateBiz = messageTemplateBiz;
            _messageTokenProvider = messageTokenProvider;
        }

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            var model = new MessageTemplateSearchModel();
            model.SetGridPageSize();
            return View(model);
        }

        [HttpPost]
        public JsonResult List(DataSourceRequest command, MessageTemplateSearchModel model)
        {
            var ls = _messageTemplateBiz.GetAllMessageTemplates();
            var dataModel = ls.Select(x => x.ToModel());
            return Json(new { data = dataModel });
        }
        [HttpGet]
        public ActionResult Create()
        {
            var model = new MessageTemplateModel();
            return View(model);
        }
        [HttpPost]
        public virtual IActionResult Create(MessageTemplateModel model)
        {
            if (ModelState.IsValid)
            {
                var messageTemplate = model.ToEntity();
                _messageTemplateBiz.InsertMessageTemplate(messageTemplate);
                return RedirectToAction("List");
            }
            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var currentMessageTemplate = _messageTemplateBiz.GetMessageTemplateById(Id);
            if (currentMessageTemplate == null)
            {
                return Json("Cannot retreive data");
            }
            var model = currentMessageTemplate.ToModel();

            var allowedTokens = string.Join(", ", _messageTokenProvider.GetListOfAllowedTokens(_messageTokenProvider.GetTokenGroups(currentMessageTemplate)));
            model.AllowedTokens = $"{allowedTokens}{Environment.NewLine}{Environment.NewLine}" +
                $"All tokens{Environment.NewLine}";
            return View("Edit", model);
        }
        [HttpPost]
        [FormValueRequired("save")]
        public ActionResult Edit(MessageTemplateModel model)
        {
            var currentMessageTemplate = _messageTemplateBiz.GetMessageTemplateById(model.Id);

            if (string.IsNullOrEmpty(model.Body))
                model.Body = string.Empty;
            currentMessageTemplate.Body = model.Body;
            currentMessageTemplate.Subject = model.Subject;

            _messageTemplateBiz.UpdateMessageTemplate(currentMessageTemplate);

            // return Json(true);
            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            var currentMessageTemplate = _messageTemplateBiz.GetMessageTemplateById(id);
            if (currentMessageTemplate != null)
                _messageTemplateBiz.DeleteMessageTemplate(currentMessageTemplate);
            return RedirectToAction("List");
        }

        [HttpPost, ActionName("Edit")]
        public virtual IActionResult CopyTemplate(MessageTemplateModel model)
        {
            return View();
        }

        public virtual IActionResult TestTemplate(int id)
        {
            var currentMessageTemplate = _messageTemplateBiz.GetMessageTemplateById(id);
            var model = currentMessageTemplate.ToModel();
            return View(model);
        }

        [HttpPost, ActionName("TestTemplate")]
        public virtual IActionResult TestTemplate(MessageTemplateModel model)
        {
            return View(model);
        }

    }
}

Narnia.Web/Areas/Admin/Views/MessageTemplate/Create.cshtml
@using Narnia.Web.Areas.Admin.Models.Messaging;
@model MessageTemplateModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    Html.SetActiveMenuItemSystemName("MessageTemplates");
}
<form asp-controller="MessageTemplate" asp-action="Create" method="post" id="messagetemplate-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Add New
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">Back to List</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                Save
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                Save And Continue
            </button>

        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Narnia.Web/Areas/Admin/Views/MessageTemplate/Edit.cshtml
@using Narnia.Web.Areas.Admin.Models.Messaging;
@model MessageTemplateModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    Html.SetActiveMenuItemSystemName("MessageTemplates");
}

<form asp-controller="MessageTemplate" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Edit Message Template - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">Back</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                Save
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                Save And Continue
            </button>
            <span id="message-template-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                Delete
            </span>
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<narnia-delete-confirmation asp-model-id="@Model.Id" asp-button-id="message-template-delete" />

Narnia.Web/Areas/Admin/Views/MessageTemplate/List.cshtml
@using Narnia.Web.Areas.Admin.Models.Messaging;
@model MessageTemplateSearchModel
@{
    ViewBag.Title = "Message templates";
    Html.SetActiveMenuItemSystemName("MessageTemplates");
}
<narnia-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        Message templates
    </h1>
</div>
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="templates-grid"></div>
                    <script>
                        $(document).ready(function () {
                            $("#templates-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "MessageTemplate"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: function() {
                                                var data = {
                                                };
                                                addAntiForgeryToken(data);
                                                return data;
                                            }
                                        }
                                    },
                                    schema: {
                                        data: "data",
                                        total: "total",
                                        errors: "errors"
                                    },
                                    error: function (e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(Model.PageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(Model.AvailablePageSizes)],
                                    @await Html.PartialAsync("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                    {
                                        field: "name",
                                        title: "Name"
                                    }, {
                                        field: "subject",
                                        title: "Subject"
                                    }, {
                                        field: "isActive",
                                        title: "Active",
                                        width: 100,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '# if(isActive) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                    },
                                    {
                                        field: "id",
                                        title: "Edit",
                                        width: 100,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '<a class="btn btn-default" href="Edit/#=id#"><i class="fa fa-pencil"></i>Edit</a>'
                                    }
                                ]
                            });
                        });
                    </script>
                    <script>
                        $(document).ready(function () {
                            //search button
                            $('#search-templates').click(function () {
                                //search
                                var grid = $('#templates-grid').data('kendoGrid');
                                grid.dataSource.read();
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>











Narnia.Web/Areas/Admin/Views/MessageTemplate/TestTemplate.cshtml
@using Narnia.Web.Areas.Admin.Models.Messaging;
@model MessageTemplateModel
@{
    Layout = null;
}

@if (Model != null)
{
    @Html.Raw(Model.Body)
}
else
{
    <h1>No template found!</h1>
}

Narnia.Web/Areas/Admin/Views/MessageTemplate/_CreateOrUpdate.cshtml
@using Narnia.Web.Areas.Admin.Models.Messaging
@model MessageTemplateModel
@Html.ValidationSummary(false)
@Html.HiddenFor(model => model.Id)

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="margin-bottom">
                        <em> Edit message template - @Model.Name</em>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <narnia-label asp-for="AllowedTokens" />
                        </div>
                        <div class="col-md-9">
                            <a id="allowedTokensShowHide" href="javascript:toggleLoadedAllowedTokens();">Show</a>
                            <div id="pnlAllowedTokens" style="display: none; white-space: pre-line">
                                <div class="form-text-row">@Model.AllowedTokens</div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <narnia-label asp-for="Name" />
                        </div>
                        <div class="col-md-9">
                            <div class="form-text-row">@Model.Name</div>
                            <input asp-for="Name" type="hidden" />
                        </div>
                    </div>
                    <script>
                        function toggleLoadedAllowedTokens() {
                            $('#pnlAllowedTokens').toggle();
                            if ($('#pnlAllowedTokens').css('display') == 'none') {
                                $('#allowedTokensShowHide').html('Show');
                            } else {
                                $('#allowedTokensShowHide').html('Hide');
                            }
                        }
                    </script>

                    <div class="form-group">
                        <div class="col-md-3">
                            <narnia-label asp-for="Subject" />
                        </div>
                        <div class="col-md-9">
                            <narnia-editor asp-for="Subject" asp-required="true" />
                            <span asp-validation-for="Subject"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <narnia-label asp-for="Body" />
                        </div>
                        <div class="col-md-9">
                            <div class="input-group input-group-required">
                                <narnia-editor asp-for="Body" asp-template="RichEditor" />
                                <div class="input-group-btn">
                                    <narnia-required />
                                </div>
                            </div>
                            <span asp-validation-for="Body"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <narnia-label asp-for="IsActive" />
                        </div>
                        <div class="col-md-9">
                            <narnia-editor asp-for="IsActive" />
                            <span asp-validation-for="IsActive"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            <div class="label-wrapper">
                                <label class="control-label">Test</label>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <button type="button" class="btn btn-primary" onclick="setLocation('@(Url.Action("TestTemplate", new {id = Model.Id}))')">Test</button>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>











