Narnia.Web/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FastMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Narnia.Business;
using Narnia.Core;
using Narnia.Core.Domain;
using Narnia.Core.Enums;
using Narnia.Core.Infrastructure;
using Narnia.Core.Models;
using Narnia.Web.Areas.Admin.Models.AjaxDataTables;
using Narnia.Web.Models;

namespace Narnia.Web.Controllers
{
    [Authorize]
    [Route("trades")]
    public class TradesController : Controller
    {
        private readonly User _currentUser;
        private readonly ITransactionBiz _transactionBiz;
        public TradesController(ITransactionBiz transactionBiz)
        {
            _transactionBiz = transactionBiz;
            _currentUser = EngineContext.Current.Resolve<IWorkContext>().CurrentUser;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("trade-history")]
        public JsonResult TransactionHistory(DataTableAjaxPostModel model, int type)
        {
            var userId = _currentUser?.Id ?? 0;

            //var searchModel = new TransactionHistorySearchModel()
            //{
            //    UserId = userId,
            //    AssetTypeId = _workContext.WorkingSymbol.AssetIdBase,
            //    TransactionType = (TransactionWalletType)type,
            //    Skip = model.start,
            //    Take = model.length
            //};
            var listData = _transactionBiz.GetTransactionHistoryForUser(userId, (TransactionStatusClient)type, model.start, model.length);
            var transactionViewModel = TypeAdapter.Adapt<IList<TransactionHistoryUserModel>, IList<TransactionHistoryViewModel>>(listData.Data.ToList());
            return Json(new DataTableAjaxReturnModel<TransactionHistoryViewModel>()
            {
                draw = model.draw,
                recordsFiltered = listData.TotalCount,
                recordsTotal = listData.TotalCount,
                data = transactionViewModel
            });
        }

        [Route("active")]
        public async Task<IActionResult> Active()
        {
            return ViewComponent("PendingTrade", null);
        }

        [Route("closed")]
        public async Task<IActionResult> Closed()
        {
            return ViewComponent("ClosedTrade", null);
        }

        [Route("completed")]
        public async Task<IActionResult> Completed()
        {
            return ViewComponent("CompletedTrade", null);
        }
    }
}

Narnia.Web/Views/Trades/Index.cshtml
@{
    ViewData["Title"] = "Wallet";
}

<link href="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>

<link href="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.css" rel="stylesheet" type="text/css" />
<script src="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>

<div class="main-content">
    <div class="col-xs-12">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#pending">Giao dịch đang chờ xử lý</a></li>
            <li><a data-toggle="tab" href="#closed">Giao dịch bị hủy</a></li>
            <li><a data-toggle="tab" href="#completed">Giao dịch đã hoàn thành</a></li>
        </ul>

        <div class="tab-content">
            <div id="pending" class="tab-pane fade in active">
                @*<a class="contentLink" style="display: none;" data-loaded="0" asp-controller="Trades" asp-action="Active">Giao dịch đang chờ xử lý</a>
        <div class="content" ></div>*@

                @*@await Component.InvokeAsync("PendingTrade", null)*@
                @{await Html.RenderPartialAsync("_TradesHistory", 1);}
            </div>
            <div id="closed" class="tab-pane fade">
                @*@await Component.InvokeAsync("ClosedTrade", null)*@
                @{await Html.RenderPartialAsync("_TradesHistory", 2);}
            </div>
            <div id="completed" class="tab-pane fade">
                @{await Html.RenderPartialAsync("_TradesHistory", 3);}

            </div>
        </div>
    </div>
</div>  

Narnia.Web/Views/Trades/_TradesHistory.cshtml
@model int

<div class="row col-md-12">
    <br />
    <div class="box-body">
        <table id="tblTradeHistory_@Model" class="table table-bordered table-striped"></table>
    </div>
</div>

<script type="text/javascript">
    var resourceTable = null;
    $(function () {

        resourceTable = $('#tblTradeHistory_@Model').DataTable(
            {
                responsive: true,
                paging: true,
                serverSide: true,
                ajax:
                {
                    url: '/trades/trade-history',
                    type: "POST",
                    data: function (d) {
                        d.type = @Model;
                    }
                },
                "searching": false,
                "pageLength": 20,
                "lengthMenu": [
                    [10, 15, 20, 25, 50],
                    [10, 15, 20, 25, 50] // change per page values here
                ],
                columns: [
                    { title: "Stt", data: "transactionId" },
                    { title: "Mã giao dịch", data: "transactionCode" },
                    { title: "Tổng số tiền", data: "amountCoin" },
                    { title: "Loại tiền", data: "assetTypeId" },
                    { title: "User tạo", data: "userAdsId" },

                    { title: "Ngày tạo", data: "createdDateDisplay" }
                ]
            });

        //$("#btnSearch").click(function () {
        //    resourceTable.ajax.reload();
        //});
    });
</script>