Narnia.Web/Models/BankAccounts/BankAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Narnia.Web.Models.BankAccounts
{
    public class BankAccountViewModel
    {
        public int Id { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string Branch { get; set; }
        public BankViewModel Bank { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

Narnia.Web/Models/BankAccounts/BankDepositInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Narnia.Web.Models.BankAccounts
{
    public class BankDepositInfo
    {
        public BankDepositInfo() { }
        public int SystemBank { get; set; }
        public decimal Amount { get; set; }
        public string OrderNo { get; set; }       
    }
}

Narnia.Web/Models/BankAccounts/BankDepositViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Narnia.Web.Models.BankAccounts
{
    public class BankDepositViewModel
    {
        public BankDepositViewModel() { }

        public List<SelectListItem> SystemBankList { get; set; }
        public List<BankAccountViewModel> SystemBankAccounts { get; set; }
        public decimal Amount { get; set; }
        public string OrderNo { get; set; }
        public DateTime BillingDate { get; set; }
    }
}

Narnia.Web/Models/Wallet/BankAccountViewModel.cs
namespace Narnia.Web.Models
{
    public class BankAccountViewModel
    {
        public int bankAccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string Branch { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
    }
}

Narnia.Web/Areas/Admin/Controllers/BankAccountController.cs
using System;
using FastMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Narnia.Business;
using Narnia.Core;
using Narnia.Core.Domain;
using Narnia.Core.Infrastructure;
using Narnia.Core.Models;
using Narnia.Web.Areas.Admin.Models.AjaxDataTables;
using Narnia.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace Narnia.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BankAccountController : BaseAdminController
    {
        private User _currentUser = null;
        private readonly IBankAccountBiz _bankAccountBiz;
        private readonly IBanksBiz _banksBiz;

        public BankAccountController(IBankAccountBiz bankAccountBiz,
            IBanksBiz banksBiz)
        {
            _bankAccountBiz = bankAccountBiz;
            _currentUser = EngineContext.Current.Resolve<IWorkContext>().CurrentUser;
            _banksBiz = banksBiz;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            return View();
        }

        [HttpPost]
        public JsonResult LoadBankAccount(DataTableAjaxPostModel model, BankAccountSearchCriteria searchCriteria)
        {
            int totalResultsCount = 0;
            var pageSize = model.length;
            var pageIndex = model.start;
            string sortString =  model.order != null && model.order.Any() ? model.order[0].column + "-" + model.order[0].dir.ToUpper() : "";

            var resultData =
                _bankAccountBiz.GetBankAccountAdminPagings(pageIndex, pageSize, sortString, out totalResultsCount);
            var result = TypeAdapter.Adapt<List<BankAccountAdminPagingModel>, List<BankAccountAdminPagingViewModel>>(resultData);

            return Json(new DataTableAjaxReturnModel<BankAccountAdminPagingViewModel>()
            {
                draw = model.draw,
                recordsFiltered = totalResultsCount,
                recordsTotal = totalResultsCount,
                data = result
            });
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new BankAccountCreateModel();
            var banks = _banksBiz.GetList();
            if (banks != null && banks.Count > 0)
            {
                model.banks = banks.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.BankName
                }).ToList();
            }
            model.IsActived = true;
            return View("Create", model);
        }

        [HttpPost]
        public JsonResult Add(BankAccountCreateModel model)
        {
            if (model.BankId == 0)
            {
                return Json(new { Error = true, Message = "Chưa chọn ngân hàng" });
            }
            if (string.IsNullOrEmpty(model.AccountName))
            {
                return Json(new { Error = true, Message = "Chưa nhập tên tài khoản" });
            }
            if (string.IsNullOrEmpty(model.AccountNo))
            {
                return Json(new { Error = true, Message = "Chưa nhập số tài khoản" });
            }
            var bankAccount = new BankAccount
            {
                UserId = CommonConst.UserIdAdmin,
                AccountName = model.AccountName,
                BankId = model.BankId,
                AccountNo = model.AccountNo,
                Branch = model.Branch,
                CreatedDate = DateTime.Now,
                IsActived = model.IsActived,
                IsDeleted = false
            };
            var result = _bankAccountBiz.CreateBankAccountAdmin(bankAccount);
            if (result.HasError)
            {
                return Json(new { Error=true,Message=result.Message });
            }
            return Json(new { Error = false, Message = "" });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = new BankAccountCreateModel();
            var bankAccount = _bankAccountBiz.GetById(id);
            var banks = _banksBiz.GetList();
            if (banks != null && banks.Count > 0)
            {
                model.banks = banks.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.BankName
                }).ToList();
            }
            if (bankAccount == null)
            {
                return View("Edit", model);
            }
            model.BankId = bankAccount.BankId;
            model.bankAccountId = bankAccount.Id;
            model.AccountName = bankAccount.AccountName;
            model.AccountNo = bankAccount.AccountNo;
            model.Branch = bankAccount.Branch;
            model.IsActived = bankAccount.IsActived;
            return View("Edit", model);
        }

        [HttpPost]
        public JsonResult Edit(BankAccountCreateModel model)
        {
            if (model.BankId == 0)
            {
                return Json(new { Error = true, Message = "Chưa chọn ngân hàng" });
            }
            if (string.IsNullOrEmpty(model.AccountName))
            {
                return Json(new { Error = true, Message = "Chưa nhập tên tài khoản" });
            }
            if (string.IsNullOrEmpty(model.AccountNo))
            {
                return Json(new { Error = true, Message = "Chưa nhập số tài khoản" });
            }
            var bankAccount = new BankAccount
            {
                Id = model.bankAccountId,
                AccountName = model.AccountName,
                BankId = model.BankId,
                AccountNo = model.AccountNo,
                Branch = model.Branch,
                IsActived = model.IsActived,
            };
            var result = _bankAccountBiz.UpdateBankAccountAdmin(bankAccount);
            if (result.HasError)
            {
                return Json(new { Error = true, Message = result.Message });
            }
            return Json(new { Error = false, Message = "" });
        }
    }
}

Narnia.Web/Controllers/BankAccountController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using FastMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Narnia.Business;
using Narnia.Business.Impl;
using Narnia.Core;
using Narnia.Core.Domain;
using Narnia.Core.Enums;
using Narnia.Core.Infrastructure;
using Narnia.Core.Models;
using Narnia.Web.Models.BankAccounts;

namespace Narnia.Web.Controllers
{
    [Authorize]
    [Route("bank-account")]
    public class BankAccountController : Controller
    {
        private readonly User _currentUser;
        private readonly IBankAccountBiz _bankAccountBiz;
        private readonly ITransactionWalletBiz _transactionWalletBiz;
        private readonly ITransactionBiz _transactionBiz;
        public BankAccountController(IBankAccountBiz bankAccountBiz,
                                    IUserBusiness userBusiness,
                                    ITransactionWalletBiz transactionWalletBiz,
                                    ITransactionBiz transactionBiz)
        {
            _currentUser = EngineContext.Current.Resolve<IWorkContext>().CurrentUser;
            _bankAccountBiz = bankAccountBiz;
            _transactionWalletBiz = transactionWalletBiz;
            _transactionBiz = transactionBiz;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("deposit")]
        public IActionResult Deposit()
        {
            var model = new BankDepositViewModel();
            var bankAccounts = _bankAccountBiz.GetListAccountAdmin();
            model.SystemBankAccounts = new List<BankAccountViewModel>();
            model.SystemBankList = new List<SelectListItem>();
            model.SystemBankList.Add(new SelectListItem() { Value = "0", Text = "Chọn Ngân Hàng" });
            foreach (var bankAcc in bankAccounts)
            {
                var ba = TypeAdapter.Adapt<BankAccountModel, BankAccountViewModel>(bankAcc);
                ba.Bank = new Models.BankViewModel();
                ba.Bank.Id = bankAcc.BankId;
                ba.Bank.BankName = bankAcc.BankName;

                model.SystemBankAccounts.Add(ba);

                model.SystemBankList.Add(new SelectListItem() { Value = bankAcc.BankId.ToString(), Text = bankAcc.BankName });
            }

            return View(model);
        }

        [HttpPost("postdeposit")]
        public async Task<JsonResult> DepositVNDPost(BankDepositInfo model, IFormFile imgEvidence)
        {
            var userId = _currentUser?.Id ?? 0;
            int evidenceId = 0;
            if (imgEvidence != null && imgEvidence.Length > 0)
            {
                var evidenceEntity = new Evidence();
                using (var stream = new MemoryStream())
                {
                    await imgEvidence.CopyToAsync(stream);
                    evidenceEntity.Image = stream.ToArray();
                    evidenceEntity.FileName = imgEvidence.FileName;
                    evidenceEntity.ContentType = imgEvidence.ContentType;
                    evidenceEntity.CreatedDate = DateTime.Now;
                }

                var resEvidence = _transactionBiz.CreateDepositEvidence(evidenceEntity, out var outEvidenceId);
                if (resEvidence.HasError == false)
                    evidenceId = outEvidenceId;
            }

            if (model.SystemBank == 0)
            {
                TempData["error"] = CommonConst.BankidEmptyForWithdrawal;
                return Json(false);
            }

            var transactionWallet = new TransactionWallet
            {
                Amount = model.Amount,
                UserId = userId,
                CreatedDate = DateTime.Now,
                BankAccountId = model.SystemBank,
                OrderNo = model.OrderNo,
                TransactionType = (int)TransactionWalletType.Deposit
            };

            var result = _transactionWalletBiz.AddTransactionVND(transactionWallet);
            if (result.HasError)
            {
                TempData["error"] = result.Message;
                return Json(false);
            }

            TempData["success"] = CommonConst.TransactionWithDepositSuccess;
            return Json(true);
        }
    }
}

Narnia.Web/Areas/Admin/Views/BankAccount/Create.cshtml
@using Narnia.Core.Models
@model BankAccountCreateModel
@{
    Layout = "";
    Html.SetActiveMenuItemSystemName("BankAccounts");
}
@using (Html.BeginForm("Add", "BankAccount", FormMethod.Post, new { id = "bankaccount-form" }))
{
    @Html.Partial("_CreateOrUpdate", Model)
}

Narnia.Web/Areas/Admin/Views/BankAccount/Edit.cshtml
@using Narnia.Core.Models
@model BankAccountCreateModel
@{
    Layout = "";
    Html.SetActiveMenuItemSystemName("BankAccounts");
}
@using (Html.BeginForm("Edit", "BankAccount", FormMethod.Post, new { id = "bankaccount-form" }))
{
    @Html.Partial("_CreateOrUpdate", Model)
}

Narnia.Web/Areas/Admin/Views/BankAccount/List.cshtml
@using Narnia.Core.Enums;
@using Narnia.Core.Helpers
@{
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    Html.SetActiveMenuItemSystemName("BankAccounts");
}

<link href="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>

<link href="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.css" rel="stylesheet" type="text/css" />
<script src="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">BankAccount Admin</h3>
    </div>
</div>

<div class="box">
    <!-- /.box-List -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a class="btn btn-danger" data-toggle="modal" href="javascript:void(0)" id="btn-add-bankaccount"> Add new <i class="fa fa-plus"></i> </a>
                </div>
            </div>
            <div class="col-md-6">
            </div>
        </div>
        <br />
        <table id="tb-setting" class="table table-bordered table-striped"></table>
    </div>
</div>


<div id="frm-edit-bankaccount" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="edit-form">
                  
        </div>
    </div>
</div>

<script type="text/javascript">
        var resourceTable = null;
        $(function () {

            //$('#txtDateFrom, #txtDateTo').datepicker({
            //    autoclose: true,
            //    format: 'mm/dd/yyyy'
            //});

            resourceTable = $('#tb-setting').DataTable(
                   {
                    paging: true,
                    serverSide: true,
                       ajax:
                       {
                           url: '@Url.Action("LoadBankAccount")',
                           type: "POST",
                            //data: function (d) {
                            //    d.TransactionType = $("#TransactionType").val();
                            //    d.CoinType = $("#CoinType").val();
                            //    d.FromDate = $("#txtDateFrom").val();
                            //    d.ToDate = $("#txtDateTo").val();
                            //    d.Status = $("#Status").val()
                            //    d.TransactionCode = $("#TransactionCode").val();
                            //}
                        },
                    "searching": false,
                       "pageLength": 20,
                    "lengthMenu": [
                        [10, 15, 20, 25, 50],
                        [10, 15, 20, 25, 50] // change per page values here
                    ],
                       columns: [
                           //{ title: "Id", data: "id" },
                           { title: "BankName", data: "bankName" },
                           { title: "AccountName", data: "accountName" },
                           { title: "AccountNo", data: "accountNo" },
                           { title: "Branch", data: "branch" },
                           { title: "CreatedDate", data: "createdDate" },
                           { title: "IsActived", data: "isActived" },

                           //{
                           //    title: "Price", data: "coinPrice", render: function (data, type, fullObject) {
                           //        if (data <= 0)
                           //            return fullObject.currencyType.rate;
                           //        else
                           //            return data;
                           //    }
                           //},
                           //{ title: "Date", data: "createdDate" },
                           //{
                           //    title: "Status", data: "approved", render: function (data, type, fullObject) {
                           //        if (data == true)
                           //            return '<input type="checkbox" checked disabled="disabled">';
                           //        else
                           //            return '<a href="javascript:void(0);" onclick="approveSellAdvertise(' + fullObject.id + ')">Approved</a>';
                           //    }
                           //},
                           {
                               mRender: function (data, type, fullObject) {
                                   var Id = fullObject.id;
                                   var url = '@Url.Action("Edit")/?Id=' + Id;
                                   return '<a id="btn-update" data-toggle="modal" onclick="getResource(\'' + url + '\')" href="javascript:void(0)" class="edit"> Edit </a>';
                               }
                           }
                       ]
                });

            $("#btnSearch").click(function () {
                resourceTable.ajax.reload();
            });
          
        });
        function getResource(url) {
            $.ajax({
                url: url,
                type: "GET",
                dataType: "html",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("#edit-form").html(data);
                    $("#frm-edit-bankaccount").modal("show");
                },
                error: function (xhr, status, errThrow) {
                    alert(errThrow);
                }
            });
        }

    $(function () {
        $('#frm-edit-bankaccount').on('hidden.bs.modal', function (e) {
            //remove all html code:
            $("#edit-form").html('');
        })
            $("#btn-add-bankaccount").click(function () {
                var newItemUrl = '@Url.Action("Add")';
                getResource(newItemUrl);
            });
    });
        function getResource(url) {
            $.ajax({
                url: url,
                type: "GET",
                dataType: "html",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("#edit-form").html(data);
                    $("#frm-edit-bankaccount").modal("show");
                },
                error: function (xhr, status, errThrow) {
                    alert(errThrow);
                }
            });
        }
</script>

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="~/Areas/Admin/assets/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

Narnia.Web/Areas/Admin/Views/BankAccount/_CreateOrUpdate.cshtml
@using Narnia.Core.Models
@model BankAccountCreateModel
@Html.ValidationSummary(false)
@Html.HiddenFor(model => model.bankAccountId)

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">BankAccount Admin Information</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="form-group">
            <label class="col-md-3 control-label">Bank</label>
            <div class="col-md-9">
                @Html.DropDownListFor(m => m.BankId,@Model.banks, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Account Name</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.AccountName, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Account No</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.AccountNo, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Branch</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.Branch, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">IsActived</label>
            <div class="col-md-9">
                @Html.CheckBoxFor(m => m.IsActived)
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-default" id="btn-Close">Close</button>
    <button type="button" name="save" class="btn btn-success" onclick="submitBankAccountForm(this)" id="btn-update">
        @(Model.bankAccountId > 0 ? "Update":"Create")
    </button>
</div>

<script type="text/javascript">
    function submitBankAccountForm(source) {
        var frmEmailAccount = $("#bankaccount-form");
        var formData = frmEmailAccount.serialize();
        if (source != null) {
            var buttonName = $(source).attr('name');
            var param = {};
            param[buttonName] = $(source).attr('value');
            //formData = formData + '&' + $.param({ buttonName: $(source).attr('value') });
            formData = formData + '&' + $.param(param);
        }

        $("#btn-update").attr("disabled", "disabled");
        $.ajax({
            cache: false,
            type: "POST",
            url: frmEmailAccount.attr("action"),
            data: formData,
            success: function (data) {
                if (data.error == false) {
                    alert("Process request successfully");
                    resourceTable.ajax.reload();
                    //jQuery.noConflict();
                    $('#frm-edit-bankaccount').modal('hide');
                } else {
                    alert(data.message);
                }
                $("#btn-update").removeAttr("disabled");
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.responeText);
                $("#btn-update").removeAttr("disabled");
            }
        });
    }
</script>