Narnia.Web/Areas/Admin/Models/Deposits/DepositModel.cs
using Narnia.Core.Domain.Payments;
using Narnia.Web.Areas.Admin.Models.Account;
using Narnia.Web.Framework.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Narnia.Web.Areas.Admin.Models.Deposits
{
    public class DepositModel : BaseEntityModel
    {     
        public decimal Amount { get; set; }
        public string AssetTypeId { get; set; }
        public int UserId { get; set; }
        public DateTime CreatedDate { get; set; }

        public DateTime UpdatedDate { get; set; }

        public DepositStatus Status { get; set; }
        public string Description { get; set; }
       
        public UserAbbrModel User { get; set; }
        public string StatusString => Enum.GetName(typeof(DepositStatus), Status);
    }
}

Narnia.Web/Areas/Admin/Models/Deposits/DepositSearchModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Narnia.Web.Framework.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Narnia.Web.Areas.Admin.Models.Deposits
{
    public class DepositSearchModel : BasePagingSearchModel
    {
        public DepositSearchModel()
        {
            Statuses = new List<int>();
            AssetTypeIds = new List<string>();

            AvailableStatuses = new List<SelectListItem>();
            AvailableAssetTypeIds = new List<SelectListItem>();
        }
       
        [DisplayName("Start Date")]
        [UIHint("DateNullable")]
        public DateTime? StartDate { get; set; }

        [DisplayName("End Date")]
        [UIHint("DateNullable")]
        public DateTime? EndDate { get; set; }

        [DisplayName("User")]
        public virtual string UserName { get; set; }

        [DisplayName("Status")]
        public List<int> Statuses { get; set; }
        public List<SelectListItem> AvailableStatuses { get; set; }

        [DisplayName("Asset Types")]
        public List<string> AssetTypeIds { get; set; }
        public List<SelectListItem> AvailableAssetTypeIds { get; set; }
    }
}

Narnia.Web/Areas/Admin/Controllers/DepositController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using FastMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Narnia.Business.Impl;
using Narnia.Business.Transactions;
using Narnia.Core.Domain;
using Narnia.Core.Domain.Payments;
using Narnia.Core.Enums;
using Narnia.Web.Areas.Admin.Models.Deposits;
using Narnia.Web.Framework.Models;

namespace Narnia.Web.Areas.Admin.Controllers
{
    public class DepositController : BaseAdminController
    {
        private readonly IPaymentBiz _paymentBiz;
        private IAssetTypeBusiness _assetTypeBiz;
        public DepositController(IPaymentBiz paymentBiz, IAssetTypeBusiness assetTypeBiz)
        {
            _paymentBiz = paymentBiz;
            _assetTypeBiz = assetTypeBiz;
        }
       
        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            var model = new DepositSearchModel();

            model.AvailableAssetTypeIds.Add(new SelectListItem { Text = "All", Value = "all" });

            var allAssetTypes = _assetTypeBiz.GetAll();
            foreach(var assetType in allAssetTypes)
            {
                model.AvailableAssetTypeIds.Add(new SelectListItem { Text = assetType.AssetTypeId, Value = assetType.AssetTypeId });
            }

            model.AvailableStatuses.Add(new SelectListItem { Text = "All", Value = "0" });

            IList<SelectListItem> depositStatuses = Enum.GetValues(typeof(DepositStatus)).Cast<DepositStatus>().
        Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() }).ToList();
            model.AvailableStatuses.AddRange(depositStatuses);

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(DepositSearchModel searchModel)
        {
            PagedListModel<DepositModel> model;
            if(searchModel.AssetTypeIds != null)
            {
                searchModel.AssetTypeIds.RemoveAll(item => item == null);
            }
          
            var deposit = _paymentBiz.SearchDeposits(searchModel.StartDate, searchModel.EndDate,searchModel.UserName,
                        searchModel.AssetTypeIds, searchModel.Statuses,searchModel.Page - 1, searchModel.PageSize);

            model = new PagedListModel<DepositModel>
            {
                Data = deposit.Data.Select(s =>
                {
                    var depositModel = TypeAdapter.Adapt<Deposit, DepositModel>(s);                    
                    return depositModel;
                }),
                Total = deposit.TotalCount
            };

            return Json(model);
        }
    }
}

Narnia.Web/Areas/Admin/Controllers/WalletController.cs
using FastMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Narnia.Business;
using Narnia.Business.Messaging;
using Narnia.Core.Domain;
using Narnia.Web.Areas.Admin.Extensions;
using Narnia.Web.Areas.Admin.Models.AjaxDataTables;
using Narnia.Web.Areas.Admin.Models.Messaging;
using Narnia.Web.Areas.Admin.Models.Wallets;
using Narnia.Web.Framework.KendoUI;
using Narnia.Web.Framework.Models;
using Narnia.Web.Framework.Mvc.Attributes;
using System.Collections.Generic;
using System.Linq;

namespace Narnia.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WalletController: BaseAdminController
    {
        private ICoinWalletBusiness _coinWalletBusiness;
        public WalletController(ICoinWalletBusiness coinWalletBusiness)
        {
            _coinWalletBusiness = coinWalletBusiness;
        }

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            var model = new WalletSearchModel();
            model.AvailableAssetTypeIds.Add(new SelectListItem { Text = "All", Value = "" });
            var allSymbols = _coinWalletBusiness.GetAllSymbols(true).ToList();
            if (allSymbols != null && allSymbols.Count > 0)
            {
                model.AvailableAssetTypeIds.AddRange(allSymbols.Select(item => new SelectListItem() {Text = item.AssetIdBase,Value = item.AssetIdBase}));
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult List(WalletSearchModel searchCriteria)
        {
            var wallets = _coinWalletBusiness.FindWallets(searchCriteria.StartDate,searchCriteria.EndDate,searchCriteria.AssetTypeIds,searchCriteria.UserName, searchCriteria.UserId,
                searchCriteria.Page - 1,searchCriteria.PageSize);

            var model = new PagedListModel<WalletModel>
            {
                Data = wallets.Data.Select(w =>
                {
                    return new WalletModel
                    {
                        Id = w.Id,
                        WalletAddress = w.WalletAddress,
                        UserName = w.User.UserName,
                        Amount = w.Amount,
                        AssetTypeId = w.AssetTypeId,
                        CreatedDate = w.CreatedDate,
                        UpdatedDate = w.UpdatedDate,
                        WalletPassword = w.WalletPassword,
                        UserId = w.UserId
                    };
                }),
                Total = wallets.TotalCount
            };
            return Json(model);
        }
    }
}

Narnia.Web/Controllers/WalletController.cs
using FastMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Narnia.Business;
using Narnia.Business.Impl;
using Narnia.Core;
using Narnia.Core.Domain;
using Narnia.Core.Enums;
using Narnia.Core.Helpers;
using Narnia.Core.Infrastructure;
using Narnia.Core.Models;
using Narnia.Web.Areas.Admin.Models.AjaxDataTables;
using Narnia.Web.Models;
using Narnia.Web.Models.Wallet;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Narnia.Web.Controllers
{
    [Authorize]
    [Route("wallet")]
    public class WalletController : Controller
    {
        private readonly User _currentUser;
        private readonly IBankAccountBiz _bankAccountBiz;
        private readonly IUserBusiness _userBusiness;
        private readonly ICoinWalletBusiness _coinWalletBusiness;
        private readonly ITransactionWalletBiz _transactionWalletBiz;
        private readonly IWithdrawBusiness _withdrawBusiness;
        private readonly IWorkContext _workContext;
        private int _userIdDefault = 0;

        public WalletController(IBankAccountBiz bankAccountBiz,
                                IUserBusiness userBusiness,
                                ICoinWalletBusiness coinWalletBusiness,
                                ITransactionWalletBiz transactionWalletBiz,
                                IWorkContext workContext,
                                IWithdrawBusiness withdrawBusiness)
        {
            _currentUser = EngineContext.Current.Resolve<IWorkContext>().CurrentUser;
            _bankAccountBiz = bankAccountBiz;
            _userBusiness = userBusiness;
            _coinWalletBusiness = coinWalletBusiness;
            _transactionWalletBiz = transactionWalletBiz;
            _workContext = workContext;
            _withdrawBusiness = withdrawBusiness;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Withdrawal");
        }

        #region coin

        //[AllowAnonymous()]
        [HttpGet("coin/deposit")]
        public IActionResult Deposit()
        {
            var model = new CoinDepositViewModel();
            var userId = _workContext.CurrentUser.Id;
            var coinType = _workContext.WorkingSymbol.AssetIdBase;

            var currentWallet = _coinWalletBusiness.GetCurrentCoinWalletByUserId(userId, coinType);

            model.CoinType = coinType;
            model.WalletAddress = currentWallet.WalletAddress;

            return View(model);
        }

        [HttpGet("coin/withdrawal")]
        public IActionResult Withdrawal()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [Route("coin/withdrawal")]
        public IActionResult Withdrawal(WithdrawViewModel model)
        {
            try
            {
                model.CoinCode = _workContext.WorkingSymbol.AssetIdBase;
                model.UserId = _currentUser.Id;
                var result = _withdrawBusiness.Withdraw(model);
                if (result.HasError)
                {
                    TempData["error"] = result.Message;
                }
                else
                {
                    TempData["success"] = "Bạn đã rút tiền thành công";
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = CommonConst.HasErrPleaseContactAdmin;
            }

            return View();
        }

        [HttpPost]
        [Route("TransactionHistory")]
        public JsonResult TransactionHistory(DataTableAjaxPostModel model, int type)
        {
            var userId = _currentUser?.Id ?? 0;

            var searchModel = new TransactionHistorySearchModel()
            {
                UserId = userId,
                AssetTypeId = _workContext.WorkingSymbol.AssetIdBase,
                TransactionType = (TransactionWalletType)type,
                Skip = model.start,
                Take = model.length
            };
            var listData = _transactionWalletBiz.GetTransactionWalletPaging(searchModel, out var totalRecords);

            return Json(new DataTableAjaxReturnModel<TransactionWalletPagingModel>()
            {
                draw = model.draw,
                recordsFiltered = totalRecords,
                recordsTotal = totalRecords,
                data = listData
            });
        }

        #endregion coin

        #region VND

        [HttpGet("vnd/deposit")]
        public IActionResult DepositVND()
        {
            var userId = _currentUser?.Id ?? _userIdDefault;
            var userData = _userBusiness.GetUserById(userId);
            if (userData == null || !userData.IsVerify)
            {
                return RedirectToAction("Verify", "Account");
            }
            var bankAccountAdmins = _bankAccountBiz.GetListAccountAdmin();
            if (bankAccountAdmins == null || bankAccountAdmins.Count == 0)
                TempData["error"] = CommonConst.HasErrPleaseContactAdmin;
            var model = new DepositVNDViewModel
            {
                banks = TypeAdapter.Adapt<List<BankAccountModel>, List<BankAccountViewModel>>(bankAccountAdmins),
            };
            return View(model);
        }

        [HttpPost("vnd/deposit")]
        public IActionResult DepositVNDPost(DepositVNDViewModel model)
        {
            var userId = _currentUser?.Id ?? _userIdDefault;//TODO:
            var userData = _userBusiness.GetUserById(userId);
            if (userData == null || !userData.IsVerify)
            {
                return RedirectToAction("Verify", "Account");
            }
            if (model.BankId == 0)
            {
                TempData["error"] = CommonConst.BankidEmptyForWithdrawal;
                return View("DepositVND", model);
            }

            var transactionWallet = new TransactionWallet
            {
                Amount = model.DepositAmount,
                UserId = userId,
                CreatedDate = DateTime.Now,
                BankAccountId = model.BankId,
                TransactionType = (int)TransactionWalletType.Deposit
            };
            var result = _transactionWalletBiz.AddTransactionVND(transactionWallet);
            if (result.HasError)
            {
                TempData["error"] = result.Message;
                return View("DepositVND", model);
            }
            TempData["success"] = CommonConst.TransactionWithDepositSuccess;
            return RedirectToAction("DepositVND");
        }

        [HttpGet("vnd/detail/{transcode}")]
        public IActionResult DetailDepositVND(string transcode)
        {
            var userId = _currentUser?.Id ?? _userIdDefault;
            var userData = _userBusiness.GetUserById(userId);
            if (userData == null || !userData.IsVerify)
            {
                return RedirectToAction("Verify", "Account");
            }
            var result = _transactionWalletBiz.GetDetailVNDByTrancodeUserId(userId, transcode);
            if (result.HasError)
            {
                TempData["error"] = result.Message;
                return RedirectToAction("DepositVND");
            }
            var model =
                TypeAdapter.Adapt<TransactionWalletDetailVNDModel, TransactionWalletDetailVNDViewModel>(
                    result.Data);
            return View(model);
        }

        [HttpPost("UploadEvidence")]
        public async Task<IActionResult> UploadEvidence(EvidenceViewModel model, List<IFormFile> Image)
        {
            if (Image != null && Image.Count > 0 && Image[0].Length > 0)
            {
                var evidenceEntity = new Evidence();
                var userId = _currentUser?.Id ?? _userIdDefault;
                using (var stream = new MemoryStream())
                {
                    await Image[0].CopyToAsync(stream);
                    evidenceEntity.Image = stream.ToArray();
                    evidenceEntity.FileName = Image[0].FileName;
                    evidenceEntity.ContentType = Image[0].ContentType;
                    evidenceEntity.CreatedDate = DateTime.Now;
                }

                var isImage = UploadHelper.IsImage(evidenceEntity.ContentType, evidenceEntity.FileName);
                if (!isImage)
                {
                    TempData["error"] = "Bằng chứng không hợp lệ.";
                    return RedirectToAction("Detail", new { transcode = model.Transcode });
                }

                var result = _transactionWalletBiz.UploadEvidenceDepositVND(evidenceEntity, model.Transcode, userId);
                if (result.HasError == false)
                {
                    TempData["success"] = CommonConst.UpdateEvidenceSuccess;
                }
                else
                {
                    TempData["error"] = result.Message;
                }
            }
            return RedirectToAction("DetailDepositVND", new { transcode = model.Transcode });
        }

        [HttpPost("vnd/cancel")]
        public IActionResult CancelTransactionVND(string transcode)
        {
            var userId = _currentUser?.Id ?? _userIdDefault;
            if (string.IsNullOrEmpty(transcode))
            {
                TempData["error"] = CommonConst.HasErrWhenCancelTransaction;
                return RedirectToAction("DetailDepositVND", new { transcode = transcode });
            }
            var result = _transactionWalletBiz.CancelTransactionVND(transcode, userId);
            if (result.HasError)
            {
                TempData["error"] = result.Message;
            }
            else
            {
                TempData["success"] = CommonConst.CancelTransactionSuccess;
            }
            return RedirectToAction("DetailDepositVND", new { transcode = transcode });

Narnia.Web/Views/Wallet/CreateAccountVND.cshtml
@{
    ViewData["Title"] = "CreateAccountVND";
}

<h2>CreateAccountVND</h2>

Narnia.Web/Views/Wallet/Deposit.cshtml
@using Narnia.Core
@using Narnia.Core.Domain
@using Narnia.Core.Infrastructure
@using Narnia.Web.Models.Wallet

@model CoinDepositViewModel

@{
    ViewData["Title"] = "Deposit";
  
}

<section class="main">
    <div class="container deposit-container">
        <h2 class="page-title">Deposit</h2>
        <p>Please send Etherium to this wallet, our system will add Etherium to your wallet automatically.</p>
        <h2>ETH Wallet</h2>
        <p>
            @*<img src="~/images/qrcode.png" alt="" />*@
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=ethereum:@Model.WalletAddress" />
        </p>
        <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3 mt-20">
            <div class="input-group">
                <input type="text" class="form-control" id="txtQrCode" name="txtQrCode" value="@Model.WalletAddress">
                <span class="input-group-addon" onclick="return copyTextToClipboard()"><i class="fa fa-copy"></i>&nbsp;Copy</span>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    function copyTextToClipboard() {
        var copyText = document.getElementById("txtQrCode");
        copyText.select();
        document.execCommand("Copy");
        //toastr.warning("Copied the text: " + copyText.value).css("width", "400px");
    }
</script>

Narnia.Web/Views/Wallet/DepositVND.cshtml
@model DepositVNDViewModel
@{
    ViewData["Title"] = "DepositVND";
}

<h2>DepositVND</h2>

<div class="col-xs-6">
    <form asp-controller="Wallet" asp-action="DepositVNDPost" method="post">
        <div class="form-group">
            <label>BankId Admin</label>
            @Html.TextBoxFor(x => x.BankId)
        </div>
        <div class="form-group">
            <label>Amount</label>
            @Html.TextBoxFor(x => x.DepositAmount)
        </div>
        <button type="submit">button</button>
    </form>
</div>

Narnia.Web/Views/Wallet/HistoryVND.cshtml
@{
    ViewData["Title"] = "HistoryVND";
}

<h2>HistoryVND</h2>

Narnia.Web/Views/Wallet/Index.cshtml
@{
    ViewData["Title"] = "Wallet";
}

Narnia.Web/Views/Wallet/Transaction.cshtml
@{
    ViewData["Title"] = "Transaction";
}

<h2>Transaction</h2>

Narnia.Web/Views/Wallet/VerifyTransactionVND.cshtml
@{
    ViewData["Title"] = "VerifyTransactionVND";
}

<h2>VerifyTransactionVND</h2>

Narnia.Web/Views/Wallet/Withdrawal.cshtml
@{
    ViewData["Title"] = "Wallet";
}

<link href="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Areas/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>

<link href="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.css" rel="stylesheet" type="text/css" />
<script src="~/Areas/Admin/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>

<div class="main-content">
    <div class="col-xs-12">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home">Rút tiền</a></li>
            <li><a data-toggle="tab" href="#deposit">Nạp tiền</a></li>
            <li><a data-toggle="tab" href="#historyTransaction">Lịch sử giao dịch</a></li>
        </ul>

        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <vc:withdraw></vc:withdraw>
            </div>
            <div id="deposit" class="tab-pane fade">
                <vc:deposit></vc:deposit>
            </div>
            <div id="historyTransaction" class="tab-pane fade">
                <div class="tab-pane active">
                    @{ await Html.RenderPartialAsync("_HistoryWalletTransaction", 0);}
                </div>
            </div>
        </div>
    </div>
</div>  

Narnia.Web/Views/Wallet/WithdrawalVND.cshtml
@model WithdrawalViewModel
@{
    ViewData["Title"] = "Rút tiền VND";
}

<h2>Rút tiền VND</h2>

<ul>
    <li>1.Chọn tại khoản</li>
    <li>2.Nhận thông tin
    <li>3.Xác nhận</li>
</ul>

<div class="col-xs-6">
    <form asp-controller="Wallet" asp-action="WithdrawalVNDPost" method="post">
        <div class="form-group">
            <label>BankId</label>
            @Html.TextBoxFor(x => x.BankId)
        </div>
        <div class="form-group">
            <label>Amount</label>
            @Html.TextBoxFor(x => x.WithdrawalAmount)
        </div>
        <button type="submit">button</button>
    </form>
</div>

Narnia.Web/Views/Wallet/_WithdrawalPartial.cshtml
@{
    ViewData["Title"] = "Wallet";
}

<div class="row">
    <div class="col-lg-12">
        <div class="deposit-container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Nạp ETHEREUM</h2>
                </div>
                <div class="panel-body text-center">
                    <div class="main-container">
                        <section class="coin-address">
                            <div class="address-text-line">
                                <div class="input-group-address-wrapper">
                                    <div class="input-group input-group-address">
                                        <div class="input-address">
                                            <div><a target="_blank" href="https://etherscan.io/tx/0x1075a29cd46290D155e09690Ff79486971705aBB">0x1075a29cd46290D155e09690Ff79486971705aBB</a></div>
                                        </div>
                                        <div class="input-group-addon"><button class="btn btn-default btn-copy-clipboard" title="Copy vào clipboard"><i class="icon-clipboard"></i></button></div>
                                    </div>
                                    <div class="input-group-address-note alert alert-warning text-left no-margin-bottom">
                                        <div>
                                            <span>Phí nạp</span><b class="coin_amount" data-ng-bind="vm.depositFee | currencyFormatter:$root.COIN_CURRENCY:'symbol':false:4">0.0050 ETH</b>
                                        </div>
                                        <div><span>Địa chỉ gửi tiền này chỉ chấp nhận ETH. Không gửi các loại coin khác vào nó.</span></div>
                                    </div>
                                </div>
                            </div>
                            <div id="deposit_qr_code">
                                <div class="qr text-center">
                                    <a class="mobile-app-hidden" href="ethereum:0x1075a29cd46290D155e09690Ff79486971705aBB" style="color: red;">
                                        <span>
                                            <img height="250" width="250" style="height: 250px; width: 250px;" />
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </section>
                        <button class="btn-generate-deposit-address btn btn-primary"><span>Tạo địa chỉ mới</span></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="pending-coin-deposit-list-container">
            <!-- react-empty: 189 -->
        </div>
        <div class="deposit-coin-list-container">
            <div class="panel panel-default list-coin-deposits">
                <div class="panel-heading">
                    <h4 class="panel-title">Lịch sử nạp ETHEREUM</h4>
                </div>
                <div class="panel-body">
                    <div class="content-wrapper">
                        <div>
                            <div>
                                <div class="loading-container text-center">
                                    <div class="loading-bar"></div>
                                </div>
                                <div>
                                    <div class="no-order-message text-center">Chưa có giao dịch.</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>